#define Reason_for_reset "Raison du redémarrage"
#define Starting_System "Démarrage du système"
#define Start_filesystem "Démarrage du système de fichiers \r\n"
#define Loading_wifi_configuration "Chargement de la configuration wifi \r\n"
#define mDNS_Responder_Started "mDNS responder démarré \r\n"
#define End_Start "Fin du démarrage "
#define Stop_minuteur "Arrêt du minuteur\r\n"
#define Stop_minuteur_temp "Arrêt du minuteur T°max\r\n"
#define Start_minuteur "Démarrage du minuteur\r\n"
#define Stop_minuteur_relay1 "Arrêt du relay1\r\n"
#define Start_minuteur_relay1 "Démarrage du relay1\r\n"
#define Stop_minuteur_relay2 "Arrêt du relay2\r\n"
#define Start_minuteur_relay2 "Démarrage du relay2\r\n"
#define Start_Wifi_Network "Démarrage du réseau Wifi "
#define timeout_AP_mode "délai d'attente dépassé, passage en mode AP \r\n"
#define Wifi_State "Etat du Wifi :"
#define Wifi_connected "Wifi connecté \r\n"
#define signal_level "force du signal :"
#define Alerte_Dallas_not_found "Alerte Dallas non trouvée\r\n"
#define found_Address "Dallas trouvée. Adresse : "
#define Dallas_lost "Dallas perdue "
#define Security_off "Sécurité désactivée\r\n"
#define Security_on "Sécurité activée\r\n"
#define Prob_not_connected "Sonde SCT-013 non connectée ?\r\n"
#define Attempting_MQTT_connexion "Tentative de connexion MQTT\r\n"
#define MQTT_connected "MQTT connecté\r\n"
#define Dimmer_found "Dimmer trouvé : "
#define Wifi_reconnected "Wifi reconnecté\r\n"
#define Wifi_disconnected "Wifi déconnecté\r\n"
#define Serial_service_stopped "Service série arrêté\r\n"
#define FS_version_is_not_same "La version du FS n'est pas à jour\r\n"
#define logs_loaded "logs chargés\r\n"
#define Fail_mount_FS "Impossible de monter le FS\r\n"
#define no_sinus_check_power "Pas de sinus, vérifiez l'alimentation 12AC\r\n"
#define FS_version_is_same "La version du FS est à jour\r\n"

////////////////////////

#define FAIL_CONF "impossible d'ouvrir le fichier de configuration en écriture dans la fonction Enregistrer la configuration"
#define Load_configuration "Chargement de la configuration \r\n"
#define Load_configuration_MQTT "Chargement de la configuration MQTT \r\n"
#define Loading_minuterie "Chargement de la minuterie"
#define Start_Wifiautoconnect "Démarrage de Wifiautoconnect \r\n"
#define DALLAS_detected " DALLAS détecté\r\n"
#define Alert_Temp "Alerte Température\r\n"
#define Dallas_Dallas_master_not_found "Dallas Maitre non trouvée\r\n"
#define HTTP_power_at "HTTP puissance à"

#define Failed_write_wifi_config "Impossible d'écrire la configuration wifi\r\n"   
#define Clear_alarm_temp "retrait de l'alarme de température \r\n"
#define Subscribe_MQTT "S'abonner et publier sur les sujets MQTT\r\n"
#define Dallas_sensor "Capteur Dallas "
#define Connecting_MQTT "Connexion à MQTT... "
